on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create new Application
        uses: ./ 
        with:
          adminApplicationId: ${{ secrets.ADMINCLIENTID }}
          adminApplicationSecret: ${{ secrets.ADMINCLIENTSECRET }}
          tenantId: ${{ secrets.TENANTID }}
          applicationName: 'MyApp'
      - name: Create new Application with Secret
        uses: ./ 
        with:
          adminApplicationId: ${{ secrets.ADMINCLIENTID }}
          adminApplicationSecret: ${{ secrets.ADMINCLIENTSECRET }}
          tenantId: ${{ secrets.TENANTID }}
          requireSecret: true
          applicationName: 'MyAppWithSecret'

      - name: Display client ID
        run: echo "The new app can be identified with ${{ steps.hello.outputs.clientId }}"
