on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build 
        run: npm install && tsc
      - name: Create new Application with Secret
        uses: ./lib
        with:
          adminApplicationId: ${{ secrets.ADMINCLIENTID }}
          adminApplicationSecret: ${{ secrets.ADMINCLIENTSECRET }}
          tenantId: ${{ secrets.TENANTID }}
          requireSecret: true
          applicationName: 'MyAppWithSecret'
          redirectUrl: 'http://localhost:8000/redirect,https://myapp.awesome.com/redirect'
          logoutUrl: 'https://myapp.awesome.com/logout'
          allowImplicitIdToken: "true"
      - name: Display client ID
        run: echo "The new app can be identified with ${{ steps.SimpleApp.outputs.clientId }}"
